Install homebrew using Ansible role (#39)
* Ansible: add --ask-become-pass

* Ansible: install external roles from requirements.yml

* Ansible: install ansible using pip

* Ansible: install Homebrew using Ansible role

* Test: uninstall pre-installed Homebrew

* Test: Use GitHub Action to setup Python

* Revert "Test: Use GitHub Action to setup Python"

This reverts commit 38a28ee64a31ae7378e3bd642f6cd12ee07d435e.

* Test: Update $PATH

* Test: debug output $PATH

* Test: check PATH

* Test: try setup-python GH action once again

* Test: use Python 3.7

* Test: get rid of Python GH action

* Test: read python version from ~/Library/Python

* Test: Remove browser installs

* Test: remove comments

* Other: Update README.md

Close #37

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,13 +1,12 @@
 #!/usr/bin/env bash
 set -e
 
-if ! [ -x "$(command -v brew)" ]; then
-  echo "Homebrew missing - please install manually using instructions on https://brew.sh/"
-  exit 1
-fi
-
 if ! [ -x "$(command -v ansible)" ]; then
-  brew install ansible
+  echo "Ansible missing - please install manually:"
+  echo
+  echo "$ sudo pip3 install --upgrade pip"
+  echo "$ pip3 install ansible"
+  exit 1
 fi
 
 if [ "${1}" == "--bootstrap" ]; then
@@ -32,7 +31,8 @@ if [ -z "${tags}" ]; then
   tags="all"
 fi
 
-ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-playbook ~/.dotfiles/dotfiles.yml --tags "${tags}" ${skipargs}
+ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-galaxy install -r ~/.dotfiles/requirements.yml &>/dev/null
+ANSIBLE_CONFIG=~/.dotfiles/ansible.cfg ansible-playbook ~/.dotfiles/dotfiles.yml --ask-become-pass --tags "${tags}" ${skipargs}
 
 if command -v terminal-notifier 1>/dev/null 2>&1; then
   terminal-notifier -title "dotfiles: Bootstrap complete" -message "Successfully set up environment."
