Rename variables

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -2,41 +2,41 @@
 
 COMMAND="satisfy"
 FULLHOST=$(hostname -f)
-CURRENTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+DOTFILEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 # Check if bork repo exists
-if [[ ! -d "${CURRENTDIR}/bork/.git" ]]; then
+if [[ ! -d "${DOTFILEDIR}/bork/.git" ]]; then
     echo "missing: bork"
-    git clone https://github.com/frdmn/bork.git ${CURRENTDIR}/bork >/dev/null && echo "ok: bork" || echo "error: bork"
+    git clone https://github.com/frdmn/bork.git ${DOTFILEDIR}/bork >/dev/null && echo "ok: bork" || echo "error: bork"
 else
     # Check if bork is up to date
-    REMOTEHEAD=$(git --git-dir=${CURRENTDIR}/bork/.git --work-tree=${CURRENTDIR}/bork ls-remote origin -h refs/heads/master | awk '{ print $1 }')
-    LOCALHEAD=$(git --git-dir=${CURRENTDIR}/bork/.git --work-tree=${CURRENTDIR}/bork rev-parse HEAD)
+    REMOTEHEAD=$(git --git-dir=${DOTFILEDIR}/bork/.git --work-tree=${DOTFILEDIR}/bork ls-remote origin -h refs/heads/master | awk '{ print $1 }')
+    LOCALHEAD=$(git --git-dir=${DOTFILEDIR}/bork/.git --work-tree=${DOTFILEDIR}/bork rev-parse HEAD)
     if [[ $REMOTEHEAD == $LOCALHEAD ]]; then
         echo "ok: bork"
     else
         echo "outdated: bork"
-        git --git-dir=${CURRENTDIR}/bork/.git --work-tree=${CURRENTDIR}/bork pull
+        git --git-dir=${DOTFILEDIR}/bork/.git --work-tree=${DOTFILEDIR}/bork pull
         echo "ok: bork"
     fi
 fi
 
 # Make sure dotfile repo is up to date
-git --git-dir=${CURRENTDIR}/bork/.git pull >/dev/null && echo "ok: dotfiles" || echo "error: dotfiles"
+git --git-dir=${DOTFILEDIR}/bork/.git pull >/dev/null && echo "ok: dotfiles" || echo "error: dotfiles"
 
 # Check arguments
 if [[ -z ${1} ]]; then
     # If no 2nd argument => use bootstrap borkfile
-    ${CURRENTDIR}/bork/bin/bork ${COMMAND} borkfiles/_.bork
+    ${DOTFILEDIR}/bork/bin/bork ${COMMAND} borkfiles/_.bork
 
     # Host specific
-    if [ "$(ls ${CURRENTDIR}/hostnames/${FULLHOST}/borkfiles 2> /dev/null)" ]; then
+    if [ "$(ls ${DOTFILEDIR}/hostnames/${FULLHOST}/borkfiles 2> /dev/null)" ]; then
       # Change into the host specific borkfile folder. Hack to avoid bork appending the fullpath a second time
       echo "info: found host-specific bork files for \"${FULLHOST}\""
-      cd ${CURRENTDIR}/hostnames/${FULLHOST}/borkfiles
+      cd ${DOTFILEDIR}/hostnames/${FULLHOST}/borkfiles
       for file in *; do
         # Execute without location paths
-        ${CURRENTDIR}/bork/bin/bork ${COMMAND} "${file}"
+        ${DOTFILEDIR}/bork/bin/bork ${COMMAND} "${file}"
       done
       # Change back into previous directory
       cd - >/dev/null
@@ -50,7 +50,7 @@ else
             # Expand to actual path of borkfile, append to $BORKFILESTRING
             BORKFILESTRING+=" borkfiles/${BORK}.bork"
         # If host specific, use that one instead
-        elif [[ -f ${CURRENTDIR}/hostnames/${FULLHOST}/borkfiles/${BORK}.bork ]]; then
+        elif [[ -f ${DOTFILEDIR}/hostnames/${FULLHOST}/borkfiles/${BORK}.bork ]]; then
             # Expand to actual path of borkfile, append to $BORKFILESTRING
             echo "info: found host-specific bork files for \"${FULLHOST}\""
             BORKFILESTRING+=" hostnames/${FULLHOST}/borkfiles/${BORK}.bork"
@@ -61,6 +61,6 @@ else
     # Check if we have found at least one valid borkfile
     if [[ ! -z ${BORKFILESTRING} ]]; then
         # Execute $BORKFILESTRING
-        ${CURRENTDIR}/bork/bin/bork ${COMMAND} ${BORKFILESTRING}
+        ${DOTFILEDIR}/bork/bin/bork ${COMMAND} ${BORKFILESTRING}
     fi
 fi
